# Generated by Django 2.2.6 on 2019-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preface',
            field=models.TextField(default='Hello'),
        ),
    ]
