# Generated by Django 2.2.6 on 2019-11-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_post_preface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preface',
            field=models.CharField(default='Hello', max_length=500),
        ),
    ]
