# Generated by Django 2.2.6 on 2019-11-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_auto_20191124_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='TestApp.PostCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
