# Generated by Django 2.2.6 on 2019-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0006_auto_20191124_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
    ]
