# Generated by Django 2.2.6 on 2019-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0007_remove_post_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_slug',
        ),
    ]
