# Generated by Django 2.2.6 on 2019-11-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0009_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
