# Generated by Django 2.2.6 on 2019-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0011_auto_20191124_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
